# Generated by Django 3.2.6 on 2021-10-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_created',
            new_name='category_created',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_weight',
            new_name='category_weight',
        ),
    ]
