# Generated by Django 3.2.6 on 2021-10-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='category_name',
            new_name='category',
        ),
    ]
