# Generated by Django 3.2.6 on 2021-10-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20211019_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_vat',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
    ]
