# Generated by Django 3.2.6 on 2021-10-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_category_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
