# Generated by Django 3.2.6 on 2021-10-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_category_name_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
