# Generated by Django 3.2.6 on 2021-10-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20211024_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=50),
        ),
    ]
