# Generated by Django 3.2.6 on 2021-10-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_delivery_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='quantity',
        ),
    ]
