# Generated by Django 3.2.6 on 2021-10-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_rename_amount_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category.order'),
        ),
    ]
