# Generated by Django 3.2.6 on 2021-10-20 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20211020_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='order_id',
            field=models.OneToOneField(default='ord-1', on_delete=django.db.models.deletion.CASCADE, to='category.order'),
        ),
    ]
